# Generated by Django 5.1.7 on 2025-03-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('Current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('Dropoff_location', models.CharField(max_length=255)),
                ('Current_cycle_using', models.CharField(max_length=255)),
                ('trip_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
